language: python
python:
  - "3.6"

sudo: True #in order to get Miniconda

before_install:
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment 
  - source activate test-environment
  - "pip install sphinx"
  - "pip install ipywidgets"
  - "pip install sphinx_bootstrap_theme"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"

install:
  - conda config --add channels/dev diffpy
  - conda install diffpy.structure
  - "pip install . -r requirements.txt"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - pytest --cov=pyxem -p no:warnings tests 
  - sphinx-apidoc -fo docs/source pyxem
  - sphinx-build -b html docs/source docs/build
after_success:
  - coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master

matrix:
  allow_failures:
    - script: sphinx-apidoc -fo docs/source pyxem
    - script: sphinx-build -b html docs/source docs/build
