language: python
python:
  - "3.6"

sudo: false

before_install:
  - "pip install sphinx hyperspy pymatgen"
  - "pip install Cython transforms3d lxml ipywidgets scikit-learn
  - "pip install sphinx_bootstrap_theme"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"

install:
  - "python setup.py install"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - pytest --cov=pyxem tests
  - sphinx-apidoc -fo docs/source pyxem
  - sphinx-build -b html docs/source docs/build
after_success:
  - coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ${TRAVIS_BUILD_DIR}/docs/build
  on:
    branch: continuous-integration

matrix:
  allow_failures:
    - script: sphinx-apidoc -fo docs/source pyxem
    - script: sphinx-build -b html docs/source docs/build
