language: python

env:
  global:
    - DEPS="hyperspy-base diffsims lmfit pyfai"
    - TEST_DEPS="pytest pytest-cov coveralls"

matrix:
  include:
  - env: export PYTHON=3.8        
  - env: export PYTHON=3.7
  - env: export PYTHON=3.7
    os: osx
    osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4 - taken from https://docs.travis-ci.com/user/languages/python/#examples
    language: shell

sudo: True #for Miniconda

before_install:
  # Install miniconda
  - if [ $TRAVIS_OS_NAME = osx ]; then
      curl "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -o miniconda.sh;
    else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    hash -r;
  # setup environment
  - source $HOME/miniconda/bin/activate root;
  - conda update -y conda;
  - conda config --append channels conda-forge;
  - conda create -n testenv --yes python=$PYTHON;
  - conda activate testenv;
  - conda info -a
  - df -h

install:
  - conda install -y $DEPS $TEST_DEPS;
  - pip install .

script:
  - export MPLBACKEND=Agg
  - pytest --pyargs pyxem --cov=pyxem

after_success:
  - coveralls
