# environment variables
environment:

  global:
    DEPS: "hyperspy-base diffsims"
    TEST_DEPS: "pytest"
    MPLBACKEND: "agg"

  matrix:
    - PY_VERSION: 3.7
    - PY_VERSION: 3.6
# scripts that run after cloning repository
install:
  # Workaround for https://github.com/conda/conda/issues/7144
  # see https://github.com/appveyor/ci/issues/2270
  - set PATH=C:\Miniconda37-x64;C:\Miniconda37-x64\Scripts;%PATH%

  # Activate miniconda root environment
  - "C:\\Miniconda37-x64\\Scripts\\activate.bat"

  # Setup miniconda environment.
  - ps: Add-AppveyorMessage "Setup miniconda environment..."
  - "conda update -y -n base conda"
  - 'conda config --add channels conda-forge'
  - "conda create -y -n testenv python=%PY_VERSION%"
  - "conda activate testenv"

  # Install the dependencies of pyxem.
  - 'conda install -yq %DEPS% %TEST_DEPS%'

  # Install our package
  - 'pip install -e .'

build: off

test_script:
  - 'pytest'

after_test:
  - 'python setup.py bdist_wheel'

artifacts:
  - path: dist\*.whl
    name: wheel
